.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. tcoin_qt test_tcoin_qt
clean: FORCE
	$(MAKE) -C .. tcoin_qt_clean test_tcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_tcoin_qt_check
tcoin-qt tcoin-qt.exe: FORCE
	 $(MAKE) -C .. tcoin_qt
